# Generated by Django 4.2 on 2023-04-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=255)),
                ('bad_cost', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('screen_size', models.CharField(max_length=255)),
                ('screen_dimensions', models.CharField(max_length=255)),
                ('matrix_type', models.CharField(max_length=255)),
                ('max_brightness', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('glass', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('storage', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('cores', models.CharField(max_length=255)),
                ('cpu_frequency', models.CharField(max_length=255)),
                ('main_camera', models.CharField(max_length=255)),
                ('front_camera', models.CharField(max_length=255)),
                ('video', models.CharField(max_length=255)),
                ('sims', models.CharField(max_length=255)),
                ('sim_type', models.CharField(max_length=255)),
                ('battery', models.CharField(max_length=255)),
                ('android', models.CharField(max_length=255)),
                ('warranty', models.CharField(max_length=255)),
            ],
        ),
    ]
