# Generated by Django 4.2 on 2023-04-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_phones_img_alter_phones_android_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='uuid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
